services:
 # PostgreSQL cho Hive Metastore
 postgres:
   image: postgres:15
   container_name: hive-postgres
   env_file: .env
   environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
   ports:
     - "5433:5432"
   volumes:
     - hive_postgres_data:/var/lib/postgresql/data
   healthcheck:
     test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
     interval: 10s
     retries: 5
 # Hive Metastore Service
 hive-metastore:
   image: apache/hive:4.0.0-beta-1
   container_name: hive-metastore
   depends_on:
     postgres:
       condition: service_healthy
   ports:
     - "9083:9083"
   env_file: .env
   volumes:
     - ./hive-site.xml:/opt/hive/conf/hive-site.xml:ro
     - ./postgresql-42.7.7.jar:/opt/hive/lib/postgresql-42.7.7.jar:ro
   entrypoint: >
     bash -c "schematool -dbType postgres -initOrUpgradeSchema &&
              hive --service metastore"
 # MinIO + Web Console
 minio:
   image: minio/minio:latest
   container_name: minio
   command: server /data --console-address ":9001"
   env_file: .env
   ports:
     - "9000:9000"   # S3 API
     - "9001:9001"   # MinIO Console
   volumes:
     - minio_data:/data
 # Spark Master
 spark-master:
   image: bitnami/spark:3.5.1
   container_name: spark-master
   depends_on:
     - hive-metastore
     - minio
   env_file: .env
   volumes:
     - ./hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml:ro
     - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf:ro
     - ./demo.py:/app/demo.py:ro
     - ./hadoop-aws-3.3.4.jar:/opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar:ro
     - ./aws-java-sdk-bundle-1.12.262.jar:/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar:ro
     - ./hadoop-client-3.3.4.jar:/opt/bitnami/spark/jars/hadoop-client-3.3.4.jar:ro
     - ./postgresql-42.7.7.jar:/opt/jars/postgresql-42.7.7.jar:ro
   environment:
     - SPARK_MODE=master
     - SPARK_MASTER_HOST=spark-master
     - SPARK_MASTER_PORT=7077
     - SPARK_MASTER_WEBUI_PORT=8080
   ports:
     - "7077:7077"   # Spark master port
     - "8080:8080"   # Spark master Web UI
 # Spark Worker #1
 spark-worker-1:
   image: bitnami/spark:3.5.1
   container_name: spark-worker-1
   depends_on:
     - spark-master
   env_file: .env
   volumes:
     - ./hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml:ro
     - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf:ro
     - ./hadoop-aws-3.3.4.jar:/opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar:ro
     - ./aws-java-sdk-bundle-1.12.262.jar:/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar:ro
     - ./hadoop-client-3.3.4.jar:/opt/bitnami/spark/jars/hadoop-client-3.3.4.jar:ro
     - ./postgresql-42.7.7.jar:/opt/jars/postgresql-42.7.7.jar:ro
   environment:
     - SPARK_MODE=worker
     - SPARK_MASTER_URL=spark://spark-master:7077
     - SPARK_WORKER_WEBUI_PORT=8081
   ports:
     - "8081:8081"   # Worker 1 Web UI
 # Spark Worker #2
 spark-worker-2:
   image: bitnami/spark:3.5.1
   container_name: spark-worker-2
   depends_on:
     - spark-master
   env_file: .env
   volumes:
     - ./hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml:ro
     - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf:ro
     - ./hadoop-aws-3.3.4.jar:/opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar:ro
     - ./aws-java-sdk-bundle-1.12.262.jar:/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar:ro
     - ./hadoop-client-3.3.4.jar:/opt/bitnami/spark/jars/hadoop-client-3.3.4.jar:ro
     - ./postgresql-42.7.7.jar:/opt/jars/postgresql-42.7.7.jar:ro
   environment:
     - SPARK_MODE=worker
     - SPARK_MASTER_URL=spark://spark-master:7077
     - SPARK_WORKER_WEBUI_PORT=8082
   ports:
     - "8082:8082"   # Worker 2 Web UI
 # Spark Worker #3
 spark-worker-3:
   image: bitnami/spark:3.5.1
   container_name: spark-worker-3
   depends_on:
     - spark-master
   env_file: .env
   volumes:
     - ./hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml:ro
     - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf:ro
     - ./hadoop-aws-3.3.4.jar:/opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar:ro
     - ./aws-java-sdk-bundle-1.12.262.jar:/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar:ro
     - ./hadoop-client-3.3.4.jar:/opt/bitnami/spark/jars/hadoop-client-3.3.4.jar:ro
     - ./postgresql-42.7.7.jar:/opt/jars/postgresql-42.7.7.jar:ro
   environment:
     - SPARK_MODE=worker
     - SPARK_MASTER_URL=spark://spark-master:7077
     - SPARK_WORKER_WEBUI_PORT=8083
   ports:
     - "8083:8083"   # Worker 3 Web UI
volumes:
 hive_postgres_data:
 minio_data: