version: 2

sources:
  - name: seeds
    description: "Seed data tables"
    tables:
      - name: t24_branch
        description: "T24 branch master data"
        columns:
          - name: Branch_Code
            description: "Unique branch identifier"
            tests:
              - unique
              - not_null
          - name: Branch_Name
            description: "Branch name"
          - name: Description
            description: "Branch description and address"
          - name: Parent_Branch
            description: "Parent branch code"
          - name: Level_Code
            description: "Branch hierarchy level"
      
      - name: t24_industry
        description: "T24 industry master data"
        columns:
          - name: INDUSTRY_ID
            description: "Unique industry identifier"
            tests:
              - unique
              - not_null
          - name: INDUSTRY_NAME
            description: "Industry name"
          - name: DESCRIPTION
            description: "Industry description"
          - name: CREATED_AT
            description: "Industry creation timestamp"
